### ISSUE TITLE
Check status of a bridged tx

### ISSUE THREAD

**Issue by mdfalcon104** [synapsecns/synapse-api#29]
is there any way to check status of a bridged tx.

**Comment by bholagabbar** [comment]
@dlpigpen does https://explorer.dorime.org/#get-/api/v1/search/txhash/-txhash- satisfy your usecase ? We're discussing whether we'd like to merge this endpoint into our current API but let me know if this works for now

**Comment by mdfalcon104** [comment]
@bholagabbar 
 thanks, bro.  I think we should merge this endpoint into our current api to maintain and develop in the future. of course, if it does not take your time. Good job team!

**Comment by mdfalcon104** [comment]
One more question, do we need to claim manually in the destination chain or does the token automatically transfer to the receiver wallet address.?

**Comment by bholagabbar** [comment]
> @bholagabbar thanks, bro. I think we should merge this endpoint into our current api to maintain and develop in the future. of course, if it does not take your time. Good job team!

Take a look at the new endpoint we added, which let's you check status of bridge transaction. For now, that should solve your usecase. Feel free to reach out to our team on discord
