### ISSUE TITLE
BUSD is not working

### ISSUE THREAD

**Issue by tibt6128** [synapsecns/synapse-api#39]
BUSD bridging between BSC and Polygon is working but this estimateBridgeOutput is not working for this.It's returning that busd is not supported to polygon.

**Comment by tibt6128** [comment]
> BUSD bridging between BSC and Polygon is working on live but this estimateBridgeOutput is not working for this.It's returning that busd is not supported to polygon.

```
{
"error": "Error: Token BUSD not supported on 'to' network Polygon"
}
```

**Comment by tibt6128** [comment]
@metagabbar @BlazeWasHere @aureliusbtc @caesar0x please help.i am stuck here.

**Comment by BlazeWasHere** [comment]
> @metagabbar @BlazeWasHere @aureliusbtc @caesar0x please help.i am stuck here.

It is helpful to send a minimal reproducible code for your issue, however that error message is correct - you cannot receive BUSD on Polygon. Perhaps you meant DAI instead of BUSD, either way you can verify this on the [UI](https://synapseprotocol.com).

**Comment by ibrahim01832891988** [comment]
> > @metagabbar @BlazeWasHere @aureliusbtc @caesar0x please help.i am stuck here.
> 
> It is helpful to send a minimal reproducible code for your issue, however that error message is correct - you cannot receive BUSD on Polygon. Perhaps you meant DAI instead of BUSD, either way you can verify this on the [UI](https://synapseprotocol.com).

Thanks for reply.
I dont want to receive BUSD.I want to receive DAI on polygon by BUSD on BSC.But when i try to fetch estimatedOutput DAI amount user will get i'm receiving this error.
I'm calling api like this.
[https://syn-api-x.herokuapp.com/v1/estimate_bridge_output?fromChain=56&toChain=137&fromToken=BUSD&toToken=DAI&amountFrom=1000000000000000000](url)

**Comment by tibt6128** [comment]
> > > @metagabbar @BlazeWasHere @aureliusbtc @caesar0x please help.i am stuck here.
> > 
> > 
> > It is helpful to send a minimal reproducible code for your issue, however that error message is correct - you cannot receive BUSD on Polygon. Perhaps you meant DAI instead of BUSD, either way you can verify this on the [UI](https://synapseprotocol.com).
> 
> Thanks for reply. I dont want to receive BUSD.I want to receive DAI on polygon by BUSD on BSC.But when i try to fetch estimatedOutput DAI amount user will get i'm receiving this error. 

I'm calling api like this.
 [https://syn-api-x.herokuapp.com/v1/estimate_bridge_output?fromChain=56&toChain=137&fromToken=BUSD&toToken=DAI&amountFrom=1000000000000000000](url)


How could i know how much DAI i will receive on polygon in exchange of BUSD on BSC.It's supporting on UI.But not this apis.
Please help.
@metagabbar @BlazeWasHere @aureliusbtc @caesar0x  @trajan0x

**Comment by bholagabbar** [comment]
> > > > @metagabbar @BlazeWasHere @aureliusbtc @caesar0x please help.i am stuck here.
> > > 
> > > 
> > > It is helpful to send a minimal reproducible code for your issue, however that error message is correct - you cannot receive BUSD on Polygon. Perhaps you meant DAI instead of BUSD, either way you can verify this on the [UI](https://synapseprotocol.com).
> > 
> > Thanks for reply. I dont want to receive BUSD.I want to receive DAI on polygon by BUSD on BSC.But when i try to fetch estimatedOutput DAI amount user will get i'm receiving this error. 
> 
> I'm calling api like this.
>  [https://syn-api-x.herokuapp.com/v1/estimate_bridge_output?fromChain=56&toChain=137&fromToken=BUSD&toToken=DAI&amountFrom=1000000000000000000](url)
> 
> 
> How could i know how much DAI i will receive on polygon in exchange of BUSD on BSC.It's supporting on UI.But not this apis.
> Please help.
> @metagabbar @BlazeWasHere @aureliusbtc @caesar0x  @trajan0x 

Could you share a screenshot of the UI processing this ? BUSD isn't supported on Polygon

**Comment by tibt6128** [comment]
I already tested it.i'm sharing the tx link.
https://bscscan.com/tx/0x23cc7468fbc7dd992c4b0cee844b761a7e00b40c8ae26b778ab83bc2307e5c01

And also please check the api call i provided.

**Comment by bholagabbar** [comment]
@ibrahim01832891988 Thanks for bringing this to our notice. Issue should be resolved in dev, and once the above PR is merged, it should reflect in prod

**Comment by tibt6128** [comment]
Thanks.May i know the approximate time?
And also i tried bridging transaction api by setting values statically for busd BSC and DAI polygon.this api call is also failed to generate tx data.

**Comment by bholagabbar** [comment]
> Thanks.May i know the approximate time? And also i tried bridging transaction api by setting values statically for busd BSC and DAI polygon.this api call is also failed to generate tx data.

Not sure what API endpoint you're referring to. Can you try on [https://syn-api-dev.herokuapp.com/](https://syn-api-dev.herokuapp.com/) and let me know if you're running into the same issue ? This is our dev API endpoint where the issue has been fixed

[https://syn-api-dev.herokuapp.com/v1/estimate_bridge_output?fromChain=56&toChain=137&fromToken=BUSD&toToken=DAI&amountFrom=1000000000000000000](https://syn-api-dev.herokuapp.com/v1/estimate_bridge_output?fromChain=56&toChain=137&fromToken=BUSD&toToken=DAI&amountFrom=1000000000000000000) works for me

**Comment by metagabbar** [comment]
> Thanks.May i know the approximate time? And also i tried bridging transaction api by setting values statically for busd BSC and DAI polygon.this api call is also failed to generate tx data.

Not sure what API endpoint you're referring to. Can you try on `https://syn-api-dev.herokuapp.com/` and let me know if you're running into the same issue ?

**Comment by tibt6128** [comment]
> > Thanks.May i know the approximate time? And also i tried bridging transaction api by setting values statically for busd BSC and DAI polygon.this api call is also failed to generate tx data.
> 
> Not sure what API endpoint you're referring to. Can you try on https://syn-api-dev.herokuapp.com/ and let me know if you're running into the same issue ? This is our dev API endpoint where the issue has been fixed
> 
> https://syn-api-dev.herokuapp.com/v1/estimate_bridge_output?fromChain=56&toChain=137&fromToken=BUSD&toToken=DAI&amountFrom=1000000000000000000 works for me

I'm talking about this api
[ /generate_unsigned_bridge_txn?fromChain=56&toChain=137&fromToken=BUSD&toToken=DAI&amountFrom=10&address=0xb1a7863f407e992a5153a54b5d572e00b9b19104](url)

**Comment by bholagabbar** [comment]
> > > Thanks.May i know the approximate time? And also i tried bridging transaction api by setting values statically for busd BSC and DAI polygon.this api call is also failed to generate tx data.
> > 
> > 
> > Not sure what API endpoint you're referring to. Can you try on https://syn-api-dev.herokuapp.com/ and let me know if you're running into the same issue ? This is our dev API endpoint where the issue has been fixed
> > https://syn-api-dev.herokuapp.com/v1/estimate_bridge_output?fromChain=56&toChain=137&fromToken=BUSD&toToken=DAI&amountFrom=1000000000000000000 works for me
> 
> I'm talking about this api [ /generate_unsigned_bridge_txn?fromChain=56&toChain=137&fromToken=BUSD&toToken=DAI&amountFrom=10&address=0xb1a7863f407e992a5153a54b5d572e00b9b19104](url)

I've investigated the API call you sent me. That seems to be a bug with the SDK for this particular swap. I've created an issue on the SDK repository: https://github.com/synapsecns/sdk/issues/106 , feel free to track that. 

Development is rapid, we try to test the most we can via tests, coverage etc but sometimes things like this slip by. Thanks for letting us know, we appreciate it!

**Comment by tibt6128** [comment]
Thanks!
