### ISSUE TITLE
getBrideableTokens: return all tokens when chainid isn't specified

### ISSUE THREAD

**Issue by inconspicuous99** [synapsecns/synapse-api#42]
so that one can see all courtable tokens since each token returns which chains they're available to swap at.

for instance I stored this data internally and wrote a rust struct to query it.

**Comment by inconspicuous99** [comment]
@metagabbar

**Comment by bholagabbar** [comment]
So you basically want to see the tokens a chain supports ?

**Comment by inconspicuous99** [comment]
yeah but for all tokens at once,

would changing "get_chains_for_token" be better then? I changed getBrideable because I only cared about bridgeable tokens.

**Comment by bholagabbar** [comment]
> yeah but for all tokens at once,
> 
> would changing "get_chains_for_token" be better then? I changed getBrideable because I only cared about bridgeable tokens.

On second thought, this functionality makes sense. Implementing it.

Somewhat related note, would functionatliy from the SDKs `allNetworksSwapTokensMap()` work ? This returns a map for all chains, listing out chains it can transfer tokens onto, eg

```
{
  '1': {
    '10': [ [Token], [Token], [Token], [Token], [Token] ],
    '25': [
      [Token],
      [Token],
....
```

**Comment by bholagabbar** [comment]
> yeah but for all tokens at once,
> 
> would changing "get_chains_for_token" be better then? I changed getBrideable because I only cared about bridgeable tokens.

Changes should be on the dev API. When the above PR is merged, should be in prod (ETA ~24-48 hours)
