### ISSUE TITLE
How to get list transaction histories of a wallet

### ISSUE THREAD

**Issue by mdfalcon104** [synapsecns/synapse-api#43]
I am using this API to get a list of transactions of a wallet but today this api https://explorer.dorime.org/api/v1/search/txhash/0x2db3ead3bcd345e9ecb8b022740d2fc1ceb5b4903d36f91c1e4cbaa79e7f3a3a does not work anymore.

Is there any replacement API to  call? Thanks a lot.

**Comment by mdfalcon104** [comment]
@caesar0x Could you please take a little time to make it works?

**Comment by bholagabbar** [comment]
> I am using this API to get a list of transactions of a wallet but today this api https://explorer.dorime.org/api/v1/search/txhash/0x2db3ead3bcd345e9ecb8b022740d2fc1ceb5b4903d36f91c1e4cbaa79e7f3a3a does not work anymore.
> 
> Is there any replacement API to call? Thanks a lot.

@BlazeWasHere Explorer down ?

**Comment by bholagabbar** [comment]
> I am using this API to get a list of transactions of a wallet but today this api https://explorer.dorime.org/api/v1/search/txhash/0x2db3ead3bcd345e9ecb8b022740d2fc1ceb5b4903d36f91c1e4cbaa79e7f3a3a does not work anymore.
> 
> Is there any replacement API to call? Thanks a lot.

Working on it. We're reimplementing the entire service and making a graphql API to be able to query results more effectively. Stay tuned!

**Comment by bholagabbar** [comment]
> I am using this API to get a list of transactions of a wallet but today this api https://explorer.dorime.org/api/v1/search/txhash/0x2db3ead3bcd345e9ecb8b022740d2fc1ceb5b4903d36f91c1e4cbaa79e7f3a3a does not work anymore.
> 
> Is there any replacement API to  call? Thanks a lot.

API is up and running

**Comment by mdfalcon104** [comment]
thank you for your update
