### ISSUE TITLE
Maximum Tokens are not supported

### ISSUE THREAD

**Issue by tibt6128** [synapsecns/synapse-api#45]
Maximum tokens are not supported through api.But they're supported on UI.

**Comment by tibt6128** [comment]
@metagabbar @BlazeWasHere @aureliusbtc @caesar0x I tried with binance USDT and avalanche USDC.On UI it's working but on api it's returning error.Please help

**Comment by bholagabbar** [comment]
What API endpoint is this ? . Please send us the API request and the error message

**Comment by bholagabbar** [comment]
> Maximum tokens are not supported through api.But they're supported on UI.

Please tell us what other tokens aren't supported. I can add integration tests to make sure that code doesn't get pushed if they're not supported again

**Comment by bholagabbar** [comment]
> @metagabbar @BlazeWasHere @aureliusbtc @caesar0x I tried with binance USDT and avalanche USDC.On UI it's working but on api it's returning error.Please help

Hey @ibrahim01832891988 , it seems this issue was caused due to multiple parameters in SDK functions becoming required in the latest update, instead of optional (which the API used). Specifically, this update affected the `estimate_bridge_output` and `generate_unsigned_transaction` endpoints. I've issued a fix in the PR above, can you tell me if your API requests in dev pass on https://syn-api-dev.herokuapp.com ?


For eg, [https://syn-api-dev.herokuapp.com/v1/generate_unsigned_bridge_txn?fromChain=AVALANCHE&toChain=BSC&fromToken=USDT&toToken=USDC&amountFrom=1000&addressTo=0x2D2c027E0d1A899a1965910Dd272bcaE1cD03c22](https://syn-api-dev.herokuapp.com/v1/generate_unsigned_bridge_txn?fromChain=AVALANCHE&toChain=BSC&fromToken=USDT&toToken=USDC&amountFrom=1000&addressTo=0x2D2c027E0d1A899a1965910Dd272bcaE1cD03c22) works for me in dev

**Comment by tibt6128** [comment]
please check this out
https://syn-api-dev.herokuapp.com/v1/generate_unsigned_bridge_approval_txn?fromChain=56&fromToken=BUSD
@metagabbar

**Comment by tibt6128** [comment]
Check this also
https://syn-api-dev.herokuapp.com/v1/generate_unsigned_bridge_txn?fromChain=56&toChain=43114&fromToken=BUSD&toToken=USDC&amountFrom=10&addressTo=0xB1A7863F407E992a5153a54b5d572e00b9B19104
![aa](https://user-images.githubusercontent.com/16141927/164760983-cb75727e-2784-41e1-8a21-1c27e1d914bb.png)

**Comment by tibt6128** [comment]
Most of the tokens are not working.

**Comment by tibt6128** [comment]
> > @metagabbar @BlazeWasHere @aureliusbtc @caesar0x I tried with binance USDT and avalanche USDC.On UI it's working but on api it's returning error.Please help
> 
> Hey @ibrahim01832891988 , it seems this issue was caused due to multiple parameters in SDK functions becoming required in the latest update, instead of optional (which the API used). Specifically, this update affected the `estimate_bridge_output` and `generate_unsigned_transaction` endpoints. I've issued a fix in the PR above, can you tell me if your API requests in dev pass on https://syn-api-dev.herokuapp.com ?
> 
> For eg, https://syn-api-dev.herokuapp.com/v1/generate_unsigned_bridge_txn?fromChain=AVALANCHE&toChain=BSC&fromToken=USDT&toToken=USDC&amountFrom=1000&addressTo=0x2D2c027E0d1A899a1965910Dd272bcaE1cD03c22 works for me in dev

No it's not fixed.And this issue is not for parameters.I tried with valid params.

**Comment by bholagabbar** [comment]
> > > @metagabbar @BlazeWasHere @aureliusbtc @caesar0x I tried with binance USDT and avalanche USDC.On UI it's working but on api it's returning error.Please help
> > 
> > 
> > Hey @ibrahim01832891988 , it seems this issue was caused due to multiple parameters in SDK functions becoming required in the latest update, instead of optional (which the API used). Specifically, this update affected the `estimate_bridge_output` and `generate_unsigned_transaction` endpoints. I've issued a fix in the PR above, can you tell me if your API requests in dev pass on https://syn-api-dev.herokuapp.com ?
> > For eg, https://syn-api-dev.herokuapp.com/v1/generate_unsigned_bridge_txn?fromChain=AVALANCHE&toChain=BSC&fromToken=USDT&toToken=USDC&amountFrom=1000&addressTo=0x2D2c027E0d1A899a1965910Dd272bcaE1cD03c22 works for me in dev
> 
> No it's not fixed.And this issue is not for parameters.I tried with valid params.

Thanks for telling us the API endpoints that failed. This happened due to the response fields changing on the SDK's end. It's been fixed and changes are now visible in dev. Both the endpoints you quoted should now be working.

**Comment by tibt6128** [comment]
Native token could not be bridged.I tried ETH from ethereum chain to USDT of avalanche.But received error token type don't match.But it is working on UI.

https://syn-api-dev.herokuapp.com/v1/estimate_bridge_output?fromChain=1&toChain=43114&fromToken=ETH&toToken=USDT&amountFrom=5000000000000000000

Please help @metagabbar @BlazeWasHere @aureliusbtc  @trajan0x

**Comment by bholagabbar** [comment]
If you get an error saying token types don't match, then they can't be swapped. I'll take a closer look later but afaik this is the right behavior
