### ISSUE TITLE
Avalanche WETH_E swapType undefined

### ISSUE THREAD

**Issue by aureliusbtc** [synapsecns/synapse-api#50]
https://syn-api-dev.herokuapp.com/v1/estimate_bridge_output?fromChain=1&toChain=43114&fromToken=ETH&toToken=WETH_E&amountFrom=5000000000000000000

ETH ETH -> AVAX WETH.e (WETH_E in SDK) errors with:

```
{
    "error": "TypeError: Cannot read properties of undefined (reading 'swapType')"
}
```

**Comment by tibt6128** [comment]
{ "error": "Error: value out-of-bounds (argument="tokenIndexTo", value=-1, code=INVALID_ARGUMENT, version=abi/5.5.0)" }


https://syn-api-dev.herokuapp.com/v1/estimate_bridge_output?fromChain=1&toChain=43114&fromToken=ETH&toToken=ETH&amountFrom=5000000000000000000

**Comment by bholagabbar** [comment]
> https://syn-api-dev.herokuapp.com/v1/estimate_bridge_output?fromChain=1&toChain=43114&fromToken=ETH&toToken=WETH_E&amountFrom=5000000000000000000

Fixed

**Comment by bholagabbar** [comment]
> { "error": "Error: value out-of-bounds (argument="tokenIndexTo", value=-1, code=INVALID_ARGUMENT, version=abi/5.5.0)" }
> 
> https://syn-api-dev.herokuapp.com/v1/estimate_bridge_output?fromChain=1&toChain=43114&fromToken=ETH&toToken=ETH&amountFrom=5000000000000000000

`ETH` is a not a token on `AVALANCHE`. If you do a `get_bridgeable_tokens?chain=AVALANCHE`, you'll see that `ETH` is represented as `WETH_E` on Avalanche, aka a flavor of wrapped Ether.

So the correct request would be [https://syn-api-dev.herokuapp.com/v1/estimate_bridge_output?fromChain=1&toChain=43114&fromToken=ETH&toToken=WETH_E&amountFrom=5000000000000000000](https://syn-api-dev.herokuapp.com/v1/estimate_bridge_output?fromChain=1&toChain=43114&fromToken=ETH&toToken=WETH_E&amountFrom=5000000000000000000)
which works
