### ISSUE TITLE
Failed to generate unsigned data between eth of eth and eth of fantom

### ISSUE THREAD

**Issue by tibt6128** [synapsecns/synapse-api#54]
https://syn-api-dev.herokuapp.com/v1/generate_unsigned_bridge_txn?fromChain=1&toChain=250&fromToken=ETH&toToken=ETH&amountFrom=100&addressTo=0x2D2c027E0d1A899a1965910Dd272bcaE1cD03c22

I tried this one.But it's returning error.

**Comment by bholagabbar** [comment]
> https://syn-api-dev.herokuapp.com/v1/generate_unsigned_bridge_txn?fromChain=1&toChain=250&fromToken=ETH&toToken=ETH&amountFrom=100&addressTo=0x2D2c027E0d1A899a1965910Dd272bcaE1cD03c22
> 
> I tried this one.But it's returning error.

`toToken` for Fantom is `FTM_ETH`

**Comment by bholagabbar** [comment]
> https://syn-api-dev.herokuapp.com/v1/generate_unsigned_bridge_txn?fromChain=1&toChain=250&fromToken=ETH&toToken=ETH&amountFrom=100&addressTo=0x2D2c027E0d1A899a1965910Dd272bcaE1cD03c22
> 
> I tried this one.But it's returning error.
@ibrahim01832891988 I was leaving a DM but instead left Synapse and lost my roles lol. The swap endpoint is supported, not sure why you were getting an error: https://syn-api-dev.herokuapp.com/v1/check_swap_supported?fromChain=BSC&toChain=AVALANCHE&fromToken=BUSD&toToken=USDT
