### ISSUE TITLE
generate_unsigned_bridge_txn, estimate_bridge_output returning error

### ISSUE THREAD

**Issue by manuelhb14** [synapsecns/synapse-api#64]
When executing `generate_unsigned_bridge_txn`  and `estimate_bridge_output` requests to the endpoint, it returns an unexpected error:
```json
{
    "error": "TypeError: tokenFrom.decimals is not a function"
}
```

The queries done to get this error are the ones found in the [API Documentation](https://syn-api-x.herokuapp.com/apidoc/)

[generate_unsigned_bridge_txn request](https://syn-api-x.herokuapp.com/v1/generate_unsigned_bridge_txn?fromChain=AVALANCHE&toChain=BSC&fromToken=USDC&toToken=USDC&amountFrom=10&addressTo=0x2D2c027E0d1A899a1965910Dd272bcaE1cD03c22)
```
https://syn-api-x.herokuapp.com/v1/generate_unsigned_bridge_txn?fromChain=AVALANCHE&toChain=BSC&fromToken=USDC&toToken=USDC&amountFrom=10&addressTo=0x2D2c027E0d1A899a1965910Dd272bcaE1cD03c22
```

[estimate_bridge_output request](http://syn-api-x.herokuapp.com/v1/estimate_bridge_output?fromChain=AVALANCHE&toChain=BSC&fromToken=USDC&toToken=USDC&amountFrom=10)
```
http://syn-api-x.herokuapp.com/v1/estimate_bridge_output?fromChain=AVALANCHE&toChain=BSC&fromToken=USDC&toToken=USDC&amountFrom=10
```

Also tested it with different values but it doesn't seem to work properly.

Happy to answer further questions,

**Comment by bholagabbar** [comment]
Both of those endpoints work for me. I would suggest using `syn-api-dev.herokuapp.com` if `syn-api-x` doesn't work for you. E.i

`https://syn-api-dev.herokuapp.com/v1/generate_unsigned_bridge_txn?fromChain=AVALANCHE&toChain=BSC&fromToken=USDC&toToken=USDC&amountFrom=10&addressTo=0x2D2c027E0d1A899a1965910Dd272bcaE1cD03c22`

And

`http://syn-api-dev.herokuapp.com/v1/estimate_bridge_output?fromChain=AVALANCHE&toChain=BSC&fromToken=USDC&toToken=USDC&amountFrom=10`

![image](https://user-images.githubusercontent.com/11693595/176918583-3ee1f5be-a07a-4c4d-ad36-60dc8ac7b7c9.png)

![image](https://user-images.githubusercontent.com/11693595/176918646-8023eba6-12ac-4de3-8824-b80c06d5b51f.png)
