### ISSUE TITLE
check_swap_supported endpoint not working

### ISSUE THREAD

**Issue by pguardiario** [synapsecns/synapse-api#65]
When I do this request: 
curl --request GET 'https://syn-api-x.herokuapp.com/v1/check_swap_supported?fromChain=1&toChain=BSC&fromToken=WBTC&toToken=WBTC'

I get:
`{
    "error": "Valid arguments for fromChain, toChain, fromToken, toToken, amountFrom and amountTo must be passed"
}`

I tried passing amountTo, amountFrom various ways but always get that error

**Comment by bholagabbar** [comment]
WBTC won't be supported just as yet, we haven't added support in the SDK. There is a PR open though, will update the API when it gets merged
